apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-prod
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-prod
  path: ./infrastructure/production
  prune: true
  validation: client