apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-dev
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-dev
  path: ./infrastructure/development
  prune: true
  validation: client