apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-staging
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: staging
  path: ./infrastructure/staging
  prune: true
  validation: client