apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  chart:
    spec:
      sourceRef:
        namespace: flux-dev
  spec:
    template:
      spec:
        containers:
          - name: nginx-ingress-dev-controller
            args:
              - /nginx-ingress-controller
              - '--ingress-class=nginx-dev'
              - '--configmap=ingress/nginx-ingress-dev-controller'
  values:
    replicaCount: 1
    service:
      externalTrafficPolicy: "Local"
    scope:
      namespace: scm-dev