apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  chart:
    spec:
      sourceRef:
        namespace: flux-dev
  values:
    controller:
      name: dev-controller
    replicaCount: 1
    service:
      externalTrafficPolicy: "Local"
    scope:
      namespace: scm-dev
    ingressClass: nginx-dev